name: saferoute_app
description: A new Flutter project to help women navigate safely.
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=2.19.0 <3.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  google_maps_flutter: ^2.1.1
  firebase_core: ^2.14.0
  cloud_firestore: ^4.8.2
  firebase_auth: ^4.7.3

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
